### ISSUE TITLE
1-up mushroom trinket not working properly

### ISSUE THREAD

**Issue by Balirith** [JeffAdriaanse/The-Legend-of-Bum-bo-Windfall#26]
I have had this twice happen twice so far, not gonna grab it from now on until this is fixed. But the item doesn't work I saw my health flash back to what the trinket states upon death, but then the game over screen starts, I assume this is a bug?

**Comment by JeffAdriaanse** [comment]
Sorry for the inconvenience! I have put out a [new release](https://github.com/JeffAdriaanse/The-Legend-of-Bum-bo-Windfall/releases/tag/v1.2.2.0) that contains a fix for the bug. Thanks for bringing it to my attention.

**Comment by Balirith** [comment]
> Sorry for the inconvenience! I have put out a [new release](https://github.com/JeffAdriaanse/The-Legend-of-Bum-bo-Windfall/releases/tag/v1.2.2.0) that contains a fix for the bug. Thanks for bringing it to my attention.

No worries! your mod is really quite polished! Been having a blast playing it with the balance changes and such (still get my butt kicked like normal isaac with it XD) Good luck with patching and thanks for making an awesome mod!
